"""expand_schema_for_multi_tournament

Revision ID: 4bb60ab74106
Revises: 4375071e371a
Create Date: 2026-07-18 15:09:53.307722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb60ab74106'
down_revision: Union[str, Sequence[str], None] = '4375071e371a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_fixture_id', sa.Integer(), nullable=True),
    sa.Column('target_fixture_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('result_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_dependencies_source_fixture_id'), 'fixture_dependencies', ['source_fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_dependencies_target_fixture_id'), 'fixture_dependencies', ['target_fixture_id'], unique=False)
    
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_engine', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('odds_api_sport_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('home_advantage_elo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('neutral_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('relegation_spots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('promotion_spots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('relegation_playoff_spots', sa.Integer(), nullable=True))

    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matchday_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_team_placeholder', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('away_team_placeholder', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_id', sa.String(), nullable=True))
        batch_op.alter_column('home_team_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('away_team_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.create_index('ix_fixtures_api_id', ['api_id'], unique=False)
        batch_op.create_unique_constraint('uq_fixture_tournament_api', ['tournament_id', 'api_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('elo_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_teams_name')
        batch_op.create_index('ix_teams_name', ['name'], unique=False)
        batch_op.create_index('ix_teams_api_id', ['api_id'], unique=True)
        batch_op.create_unique_constraint('uq_team_name_country', ['name', 'country_code'])

    with op.batch_alter_table('tournament_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('promoted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('relegated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('draws', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goals_for', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goals_against', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_teams', schema=None) as batch_op:
        batch_op.drop_column('goals_against')
        batch_op.drop_column('goals_for')
        batch_op.drop_column('losses')
        batch_op.drop_column('draws')
        batch_op.drop_column('wins')
        batch_op.drop_column('points')
        batch_op.drop_column('relegated')
        batch_op.drop_column('promoted')
        batch_op.drop_column('division')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_name_country', type_='unique')
        batch_op.drop_index('ix_teams_api_id')
        batch_op.drop_index('ix_teams_name')
        batch_op.create_index('ix_teams_name', ['name'], unique=True)
        batch_op.drop_column('api_id')
        batch_op.drop_column('elo_source')
        batch_op.drop_column('team_type')

    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fixture_tournament_api', type_='unique')
        batch_op.drop_index('ix_fixtures_api_id')
        batch_op.alter_column('away_team_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('home_team_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.drop_column('api_id')
        batch_op.drop_column('away_team_placeholder')
        batch_op.drop_column('home_team_placeholder')
        batch_op.drop_column('matchday_number')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('relegation_playoff_spots')
        batch_op.drop_column('promotion_spots')
        batch_op.drop_column('relegation_spots')
        batch_op.drop_column('neutral_venue')
        batch_op.drop_column('home_advantage_elo')
        batch_op.drop_column('odds_api_sport_key')
        batch_op.drop_column('format_engine')

    op.drop_index(op.f('ix_fixture_dependencies_target_fixture_id'), table_name='fixture_dependencies')
    op.drop_index(op.f('ix_fixture_dependencies_source_fixture_id'), table_name='fixture_dependencies')
    op.drop_table('fixture_dependencies')
    # ### end Alembic commands ###
