"""add external mapping tables

Revision ID: 76088938f759
Revises: 7a0f4ef3c2a0
Create Date: 2026-08-07 15:59:48.459824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76088938f759'
down_revision: Union[str, Sequence[str], None] = '7a0f4ef3c2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_competition_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'external_id', name='uq_external_competition_mapping')
    )
    op.create_index(op.f('ix_external_competition_mappings_competition_id'), 'external_competition_mappings', ['competition_id'], unique=False)
    op.create_index(op.f('ix_external_competition_mappings_external_id'), 'external_competition_mappings', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_competition_mappings_id'), 'external_competition_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_external_competition_mappings_provider_name'), 'external_competition_mappings', ['provider_name'], unique=False)
    op.create_table('external_team_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'external_id', name='uq_external_team_mapping')
    )
    op.create_index(op.f('ix_external_team_mappings_external_id'), 'external_team_mappings', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_team_mappings_id'), 'external_team_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_external_team_mappings_provider_name'), 'external_team_mappings', ['provider_name'], unique=False)
    op.create_index(op.f('ix_external_team_mappings_team_id'), 'external_team_mappings', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_team_mappings_team_id'), table_name='external_team_mappings')
    op.drop_index(op.f('ix_external_team_mappings_provider_name'), table_name='external_team_mappings')
    op.drop_index(op.f('ix_external_team_mappings_id'), table_name='external_team_mappings')
    op.drop_index(op.f('ix_external_team_mappings_external_id'), table_name='external_team_mappings')
    op.drop_table('external_team_mappings')
    op.drop_index(op.f('ix_external_competition_mappings_provider_name'), table_name='external_competition_mappings')
    op.drop_index(op.f('ix_external_competition_mappings_id'), table_name='external_competition_mappings')
    op.drop_index(op.f('ix_external_competition_mappings_external_id'), table_name='external_competition_mappings')
    op.drop_index(op.f('ix_external_competition_mappings_competition_id'), table_name='external_competition_mappings')
    op.drop_table('external_competition_mappings')
    # ### end Alembic commands ###
