"""Initial relational schema

Revision ID: 766d253ea2b0
Revises: 
Create Date: 2026-06-06 10:25:43.205733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766d253ea2b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index(op.f('ix_competitions_name'), 'competitions', ['name'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.Column('win_streak', sa.Integer(), nullable=True),
    sa.Column('draw_streak', sa.Integer(), nullable=True),
    sa.Column('loss_streak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('elo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_history_id'), 'elo_history', ['id'], unique=False)
    op.create_index(op.f('ix_elo_history_recorded_at'), 'elo_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_elo_history_team_id'), 'elo_history', ['team_id'], unique=False)
    op.create_table('player_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_contracts_id'), 'player_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_player_contracts_player_id'), 'player_contracts', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_contracts_team_id'), 'player_contracts', ['team_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_competition_id'), 'tournaments', ['competition_id'], unique=False)
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('date_utc', sa.DateTime(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_penalty_score', sa.Integer(), nullable=True),
    sa.Column('away_penalty_score', sa.Integer(), nullable=True),
    sa.Column('has_extra_time', sa.Boolean(), nullable=True),
    sa.Column('has_penalties', sa.Boolean(), nullable=True),
    sa.Column('leg_number', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('watchability_score', sa.Float(), nullable=True),
    sa.Column('competitiveness_score', sa.Float(), nullable=True),
    sa.Column('odds_score', sa.Float(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.Column('narrative_score', sa.Float(), nullable=True),
    sa.Column('reasons_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_away_team_id'), 'fixtures', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_date_utc'), 'fixtures', ['date_utc'], unique=False)
    op.create_index(op.f('ix_fixtures_home_team_id'), 'fixtures', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_id'), 'fixtures', ['id'], unique=False)
    op.create_index(op.f('ix_fixtures_tournament_id'), 'fixtures', ['tournament_id'], unique=False)
    op.create_table('tournament_teams',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('tournament_status', sa.String(), nullable=True),
    sa.Column('final_stage_reached', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id')
    )
    op.create_index(op.f('ix_tournament_teams_team_id'), 'tournament_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_tournament_teams_tournament_id'), 'tournament_teams', ['tournament_id'], unique=False)
    op.create_table('fixture_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('odds_home', sa.Float(), nullable=False),
    sa.Column('odds_draw', sa.Float(), nullable=False),
    sa.Column('odds_away', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_odds_fixture_id'), 'fixture_odds', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_odds_id'), 'fixture_odds', ['id'], unique=False)
    op.create_index(op.f('ix_fixture_odds_recorded_at'), 'fixture_odds', ['recorded_at'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('passes_completed', sa.Integer(), nullable=True),
    sa.Column('tackles_made', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('stats_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_match_stats_fixture_id'), 'player_match_stats', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_id'), 'player_match_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_player_id'), 'player_match_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_match_stats_player_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_fixture_id'), table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index(op.f('ix_fixture_odds_recorded_at'), table_name='fixture_odds')
    op.drop_index(op.f('ix_fixture_odds_id'), table_name='fixture_odds')
    op.drop_index(op.f('ix_fixture_odds_fixture_id'), table_name='fixture_odds')
    op.drop_table('fixture_odds')
    op.drop_index(op.f('ix_tournament_teams_tournament_id'), table_name='tournament_teams')
    op.drop_index(op.f('ix_tournament_teams_team_id'), table_name='tournament_teams')
    op.drop_table('tournament_teams')
    op.drop_index(op.f('ix_fixtures_tournament_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_date_utc'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_away_team_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_competition_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_player_contracts_team_id'), table_name='player_contracts')
    op.drop_index(op.f('ix_player_contracts_player_id'), table_name='player_contracts')
    op.drop_index(op.f('ix_player_contracts_id'), table_name='player_contracts')
    op.drop_table('player_contracts')
    op.drop_index(op.f('ix_elo_history_team_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_recorded_at'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_id'), table_name='elo_history')
    op.drop_table('elo_history')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_competitions_name'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
